### PR TITLE
Changes in readme for building in Ubuntu

### PR DESCRIPTION
**Pull request by shivareddyiirs**

### CODE REVIEW

**Comment by lixun910** [comment]
Thanks! @shivareddyiirs

**Comment by shivareddyiirs** [comment]
@lixun910 after using the right  **.sh**  file to build , I am getting this error at the end. I am using Ubuntu 18.04.

Below is the error: 

> configure: error: could not find json-c/json.h
> make: *** No rule to make target 'config.status', needed by 'GDALmake.opt'.  Stop.
> make: *** No rule to make target 'config.status', needed by 'GDALmake.opt'.  Stop.
> Error! Exit

 I think some more steps needs to be added in readme for developers like me. Help me in understanding this error I would update readme and other files as I progress towards successfully building from source.

**Comment by lixun910** [comment]
@shivareddyiirs 
Yes agree. I am working on a cmake project to make it easy...
For this issue, I think it's from gdal, and you might need libjsoncpp-dev

**Comment by shivareddyiirs** [comment]
Hi,
I tried again and running the .sh file and this got resolved.
I think there were may be some problem in downloading  the requisite
package due to network issues.

Thanks

regards
Thanks & Regards
Shiva Reddy K.
Scientist/Engineer 'SD'
Indian Institute of Remote Sensing,
Indian Space Research Organisation
Department of Space
4-Kalidas Road
Dehradun
mobile: 0135-2524126

**Pull request merged**
